# Generated by Django 5.2.7 on 2025-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_gt_planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygtplanets',
            name='description',
            field=models.TextField(),
        ),
    ]
